### ISSUE TITLE
Fix hyperkitty / django_mailman3 issues

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#759]
- [ ] django_mailman3 assumes a username field exists [Issue #69](https://gitlab.com/mailman/django-mailman3/-/issues/69)
- [ ] hyperkitty assumes a `LOGIN_URL` is in the global template context [Issue #487](https://gitlab.com/mailman/hyperkitty/-/issues/487)
- [ ] hyperkitty assumes `auth.User` is the user model [Issue #486](https://gitlab.com/mailman/hyperkitty/-/issues/486)

Fix these in the cppalliance fork and contribute upstream.

**Comment by frankwiles** [comment]
Going with a different plan to have normal mailman3 site, as a separate project, OAuth against boost.org
